---
cassandra/cassandra-mesos-2.0.5-1.tgz:
  object_id: 2671be01-13d2-4603-bc69-dc5ac7fead10
  sha: !binary |-
    ZmNlNjU5YmVjMDAwOTFkMGJiODlkMTA5OTY2ZTU0YjIxMTYxZTE2OA==
  size: 28034771
chronos/chronos-2.1.0_mesos-0.14.0-rc4.jar:
  object_id: 2e28a1d4-32fc-4c7e-b5ed-b8235c899421
  sha: !binary |-
    OGJjZTZmMzBmM2NiNTkxZTE1M2U2ZDNhNGNkZjNkNTI2MWM5YThlYg==
  size: 30499060
java/jdk-1.7.0_51.tar.gz:
  object_id: 4de0384e-57e2-454a-a143-22a9a303a5e7
  sha: !binary |-
    YmVlM2IwODVhOTA0MzljODMzY2UxOGUxMzhjOWYxYTYxNTE1Mjg5MQ==
  size: 138199690
jenkins/mesos-0.17.0.hpi:
  object_id: 05342b43-18df-4ddb-84b0-09a5d96174f6
  sha: !binary |-
    NzNkYjBmYzI4NDY3YzM3MDUxODY2OTExYmIzOGU1MTQwOWMxYjRjZA==
  size: 878821
nginx/nginx-1.4.5.tar.gz:
  object_id: b9c19042-65ba-4cb8-82ae-6675b26171f3
  sha: !binary |-
    OTZjMWFlY2QzMTRmNzNhM2MzMGEwZGI4YzM5YWQxNWRkYWNiMDc0ZQ==
  size: 768728
nginx/pcre-8.34.tar.gz:
  object_id: 84641be9-6be7-4da1-9206-7b850a4eac6e
  sha: !binary |-
    ZDQ2ZTUzNzMzN2VlNzBkZjE5MDg0MDAxYTRiNjgxNWIzZDY5ZmU2Yw==
  size: 1933734
sasl/cyrus-sasl-2.1.26.tar.gz:
  object_id: 703c5060-94ae-4aa1-a6c4-7261e1e5ff5e
  sha: !binary |-
    ZDY2NjlmYjkxNDM0MTkyNTI5YmQxM2VlOTU3MzdhOGE1MDQwMjQxYw==
  size: 5220231
jenkins/jenkins-1.532.2.war:
  object_id: 8c217c24-aaf4-4fea-bf5c-22f49250bce3
  sha: !binary |-
    MzhhNzc1NmM5NmEyMDRmNzU3NDdkOGM0YjlkYTUxMGZkODg0ZWUzNg==
  size: 63525132
mesos/mesos-0.20.0.tar.gz:
  object_id: 63da6664-899e-4fa4-bc5d-0c15152e6a91
  sha: !binary |-
    MWUwYzIyOTlhZDk4NDZmMTA5ZGU0YmZjNDdhZTliYmIxMzZlNmZmYw==
  size: 27537727
maven/apache-maven-3.2.3-bin.tar.gz:
  object_id: 85dfe356-eb82-493b-a648-e3320fbb7c80
  sha: !binary |-
    MWNlNjY0MWY3ZGNiNGZkNTc4NWJlZGNkY2EyOTc5ZGE4M2Y2ZDIzZg==
  size: 6956162
zookeeper/zookeeper-3.4.6.tar.gz:
  object_id: 1a0f69b8-62b8-41bb-b157-cd68632f162f
  sha: !binary |-
    MmE5ZTUzZjU5OTBkZmUwOTY1ODM0YTUyNWZiY2FkMjI2YmY5MzQ3NA==
  size: 17699306
node/node-v0.10.32-linux-x64.tar.gz:
  object_id: a50316cd-b91e-4b1b-811b-00cca8e8af4e
  sha: !binary |-
    ZmFkZWZjMTVhOTkyZDIxYmQxOWQwZDNlYzE3NDM5MGQxZTdmY2I3Mg==
  size: 5643126
scala/scala-2.11.2.tgz:
  object_id: 909350c4-42a1-4b13-9488-3f52ba0040db
  sha: !binary |-
    OTA0ZTllZTNiYjk2ZTgzNTBiMWUwZjI1MDJhNzA0ZjgzNmMwY2RmMQ==
  size: 26488789
git/git-2.1.0.tar.gz:
  object_id: 4986fc48-80ce-4251-ae05-9aa2311ccd19
  sha: !binary |-
    ZTIyNTY0ZTE1MmUzMjQyYmM0ZmNmY2M3ZWIwNWZkZTdhNGM4M2UwNA==
  size: 4975916
ruby/ruby-2.1.2.tar.gz:
  object_id: 14bb5056-36bb-491f-8785-0e51cd04aee2
  sha: !binary |-
    YjgxOGQ1NmI0NjM4ZjE5NDkyMzkwMzg2MjNiNzYxNTE3ZDRhNTY4Ng==
  size: 15096114
ruby/rubygems-2.4.1.tgz:
  object_id: aaf919dd-5f7a-4c87-8660-890f53d8f4c7
  sha: !binary |-
    MDE2Yjk4ZDhmZmNhM2IxYWY0Yzc5Nzc4OGQ3NWMxYTY3ZjM4ZDQxZA==
  size: 437226
ruby/bundler-1.7.3.gem:
  object_id: 51f3077b-7811-41c3-885f-9aa4b6a38f6e
  sha: !binary |-
    NjE4ZmRmNzZmMzVlODczZTQ5MGUxNWNkYWM4N2JlN2Y3MjQ3ZjgxYg==
  size: 299520
ruby/yaml-0.1.6.tar.gz:
  object_id: c8e48f85-d597-4993-bf99-d903dd8d80a9
  sha: !binary |-
    ZjNkNDA0ZTExYmVjM2M0ZWZjZGRmZDE0YzQyZDQ2ZjFhYWJlMGI1ZA==
  size: 503012
marathon/marathon-0.7.0-RC4.tgz:
  object_id: f675f871-c7f6-433d-a5c4-ab04fcf7060c
  sha: !binary |-
    MThjZDI5YjRhNGEyNDdkYjlmOTJmZDQ3MmU4MWIxMTM2ZWIwNDk0Ng==
  size: 63361758
docker/bridge-utils-1.5.tar.gz:
  object_id: f220c677-8e73-4e6c-b5e7-adbff9320683
  sha: !binary |-
    MWY3MWI2ZjIyZjVkMmI2ZDIxZTE0NmY0YWMyMDgyMGFkNDJlNThlZQ==
  size: 33472
docker/autoconf-2.69.tar.gz:
  object_id: 0927a3d0-b43c-4aba-915a-d46959ae7a1b
  sha: !binary |-
    NTYyNDcxY2JjYjBkZDBmYTQyYTc2NjY1YWNmMGRiYjY4NDc5Yjc4YQ==
  size: 1927468
docker/aufs-tools_20120411-3_amd64.deb:
  object_id: 2f3cad6d-0ca6-4cf4-b75b-d48f92b87f53
  sha: !binary |-
    MmRmYzFmZTM4NmNkM2YwNWFjN2UwYjRlYmNmM2ViYzhhN2YzYjA0ZA==
  size: 91762
docker/docker-1.2.0:
  object_id: b044edeb-ac27-4f24-88c7-b13f259672d5
  sha: !binary |-
    NTQwNDU5YmM1ZDlmMWNhYzE3ZmU4NjU0ODkxODE0MzE0ZGIxNWU3Nw==
  size: 13398472
