<%
director_uuid = 'CHANGE-ME'
deployment_name = 'mesos'
num_zookeepers = 3 # Odd number
num_masters = 3 # Odd number
num_marathons = 1
num_chronos = 1
num_jenkins = 1
num_storm = 1
num_slaves = 3
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: mesos
   version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    machine_type: n1-standard-8
    preemptible: true

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      ephemeral_external_ip: true
      tags:
        - bosh
        - <%= deployment_name %>

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: n1-standard-2

  - name: slave
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: n1-highmem-8

jobs:
  - name: zookeeper
    templates:
      - name: zookeeper
    instances: <%= num_zookeepers %>
    resource_pool: default
    persistent_disk: 10240
    networks:
      - name: default
        default: [dns, gateway]

  - name: mesos-master
    templates:
      - name: mesos-master
    instances: <%= num_masters %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: marathon
    templates:
      - name: marathon
    instances: <%= num_marathons %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: chronos
    templates:
      - name: chronos
    instances: <%= num_chronos %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: jenkins
    templates:
      - name: jenkins
    instances: <%= num_jenkins %>
    resource_pool: default
    persistent_disk: 20480
    networks:
      - name: default
        default: [dns, gateway]

  - name: storm
    templates:
      - name: storm
    instances: <%= num_storm %>
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]

  - name: mesos-slave
    templates:
      - name: mesos-slave
      - name: docker
    instances: <%= num_slaves %>
    resource_pool: slave
    persistent_disk: 65536
    networks:
      - name: default
        default: [dns, gateway]

properties:
  mesos:
    principal: "principal"
    secret: "secret"
    master:
      quorum: <%= (num_masters/2) + 1 %>
      authenticate_frameworks: true
      authenticate_slaves: true

  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{deployment_name}.microbosh\n" %>
      <% end %>
