<% num_zookeepers = 3 %>
<% num_masters = 2 %>
<% num_marathons = 2 %>
<% num_chronos = 2 %>
<% num_jenkins = 1 %>
<% num_cassandras = 1 %>
<% num_slaves = 3 %>
<% deployment_name = "mesos-google" %>
<% os = "ubuntu" %>
<% tld = "microbosh" %>
<% director_uuid = "ba632e75-ac92-4f67-8a22-11560c0339f7" %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: mesos
   version: latest

compilation:
  workers: 10
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: n1-standard-8

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: dynamic
    cloud_properties:
      ephemeral_external_ip: true
      tags:
        - <%= deployment_name %>

resource_pools:
  - name: zookeeper
    network: default
    size: <%= num_zookeepers %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: master
    network: default
    size: <%= num_masters %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: marathon
    network: default
    size: <%= num_marathons %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: chronos
    network: default
    size: <%= num_chronos %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: jenkins
    network: default
    size: <%= num_jenkins %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: cassandra
    network: default
    size: <%= num_cassandras %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-standard-2

  - name: slave
    network: default
    size: <%= num_slaves %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: n1-highmem-8

jobs:
  - name: zookeeper
    templates:
      - name: zookeeper
    instances: <%= num_zookeepers %>
    resource_pool: zookeeper
    networks:
      - name: default
        default: [dns, gateway]

  - name: mesos-master
    templates:
      - name: mesos-master
    instances: <%= num_masters %>
    resource_pool: master
    networks:
      - name: default
        default: [dns, gateway]

  - name: marathon
    templates:
      - name: marathon
    instances: <%= num_marathons %>
    resource_pool: marathon
    networks:
      - name: default
        default: [dns, gateway]

  - name: chronos
    templates:
      - name: chronos
    instances: <%= num_chronos %>
    resource_pool: chronos
    networks:
      - name: default
        default: [dns, gateway]

  - name: jenkins
    templates:
      - name: jenkins
    instances: <%= num_jenkins %>
    resource_pool: jenkins
    networks:
      - name: default
        default: [dns, gateway]

  - name: cassandra
    templates:
      - name: cassandra
    instances: <%= num_cassandras %>
    resource_pool: cassandra
    networks:
      - name: default
        default: [dns, gateway]

  - name: mesos-slave
    templates:
      - name: mesos-slave
    instances: <%= num_slaves %>
    resource_pool: slave
    networks:
      - name: default
        default: [dns, gateway]

properties:
  mesos:
    master:
      quorum: <%= (num_masters/2) + 1 %>
  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
      <% end %>
